### ISSUE TITLE
Please release fix for ghc 7.4 breakage

### ISSUE THREAD

**Issue by kolmodin** [haskell/tar#15]
It'd be great if the fix in 028f2813d14380da3d99ac0b306b3cbb13731e56 would be released.
I run all tests on travis for my projects and the ones that depend on `tar` fails at the moment just because `tar` doesn't build properly.

**Comment by kolmodin** [comment]
This is still an issue for me, all travis builds are reported as failed. Any chance in releasing this any time soon?

**Comment by hvr** [comment]
@kolmodin release at https://hackage.haskell.org/package/tar-0.5.0.2 fixes this
(i.e. building `tar` with `base < 4.6 && directory >= 1.2.3`)

**Comment by kolmodin** [comment]
Awesome, thanks!
