### ISSUE TITLE
New release for GHC 8.4

### ISSUE THREAD

**Issue by vmchale** [haskell/tar#30]
Hi,

It seems that the code in this repository already works with GHC 8.4. Would it be possible to make a Hackage release to ease testing downstream?

Thanks!

**Comment by hvr** [comment]
Soon!(tm)

In the mean-time you can use https://github.com/hvr/head.hackage for pre-release testing which contains a patched `tar-0.5.0.3`

**Comment by peti** [comment]
A new release would be very much appreciated. I'm trying to update `hackage-db` for GHC 8.4.x, but I can't make progress easily because the latest `tar` release doesn't compile.

**Comment by hvr** [comment]
resolved via https://hackage.haskell.org/package/tar-0.5.1.0

**Comment by peti** [comment]
Thank you very much!
