### ISSUE TITLE
GNU Format accepts file names of unlimited length

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell/tar#31]
The check for 256 character lengths in `toTarPath` should be removed because the GNU format [does allow longer filepaths](https://www.gnu.org/software/tar/manual/html_section/tar_67.html). Maybe the check for filename length should be in Codec.Archive.Tar.Write, when the format is specified along with the path.

**Comment by brandonchinn178** [comment]
See #1

**Comment by brandonchinn178** [comment]
This issue can be closed
