### ISSUE TITLE
Links break when pointing to directories

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell/tar#34]
Instead of extracting links correctly, `emulateLinks` copies files pointed to by links. This breaks if a link points to a directory.

Possibly use [unix-compat](https://www.stackage.org/haddock/lts-11.15/unix-compat-0.5.0.1/System-PosixCompat-Files.html#v:createLink)?

Possibly related: #27

**Comment by Bodigrim** [comment]
Should have been fixed by #77.
