### ISSUE TITLE
Unpacking with pre-1980 modification dates is trouble on Windows

### ISSUE THREAD

**Issue by quasicomputational** [haskell/tar#37]
From haskell/cabal#5596, apparently unpacking an archive where any dates in it are before 1980-01-01 (the MS-DOS epoch) fails in a bad way on Windows. I think it'd be better to extract the file but allow some information loss in the file modification date, either by pre-clamping dates to a safe range on Windows or swallowing the error when trying to set it to an invalid one.

**Comment by Bodigrim** [comment]
This boils down to being more permissive in 
https://github.com/haskell/tar/blob/30752226e3527267743058a882923438e6433771/Codec/Archive/Tar/Unpack.hs#L255-L259
catching [`InvalidArgument`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-IO-Exception.html#t:IOErrorType).

**Comment by Bodigrim** [comment]
Fixed in e4d50da.
