### ISSUE TITLE
Allow map, filter, mapMaybe for Entries data structure

### ISSUE THREAD

**Issue by amigalemming** [haskell/tar#47]
I like to perform `map`, `mapMaybe`, `filter` on `Entries` while changing the element type from `Entry` to something else. I propose that either `Entry` becomes a type parameter of `Entries` or that the package documents a conversion from `Entries` to another data structure for lists with a termination element.

**Comment by Bodigrim** [comment]
As documentation suggests, you can convert to a list with `foldEntries`, do necessary manipulations and get back to `Entries` using `foldr Next Done`. There is also `mapEntries`.
