### ISSUE TITLE
Fails to extract hardlinks

### ISSUE THREAD

**Issue by hasufell** [haskell/tar#51]
Try to unpack https://downloads.haskell.org/~ghc/8.8.3/ghc-8.8.3-src.tar.xz which contains hardlinks:

* `ghc-8.6.5/libraries/bytestring/LICENSE -> ghc-8.6.5/libraries/bytestring/bench/LICENSE`

https://github.com/haskell/tar/blob/bde33fe580881f011ba5b91e9c23631877fa09ef/Codec/Archive/Tar/Unpack.hs#L110-L113

will receive:

```
"ghc-8.6.5/libraries/bytestring/LICENSE"       -- relPath
"ghc-8.6.5/libraries/bytestring/bench/LICENSE" -- relLinkTarget
```

And then concatenate to the path `ghc-8.6.5/libraries/bytestring/ghc-8.6.5/libraries/bytestring/bench/LICENSE`, which doesn't exist. So are hardlinks always "absolute" in the context of the tar root?

**Comment by Bodigrim** [comment]
Seems to be fixed by #77.
