### ISSUE TITLE
Expose more of Codec.Archive.Tar.Write

### ISSUE THREAD

**Issue by Sciencei** [haskell/tar#55]
Currently, `Codec.Archive.Tar.Write` only exports `write` (which is then in turn the only thing re-exported by an exposed module). It would be useful to have lower-level functions like `putHeader` exposed. As a motivating example, I would like to be able to write a streaming tar generator, with individual files potentially coming in as streams as well. With `putHeader` exposed I could do this.

**Comment by Bodigrim** [comment]
PRs welcome.

**Comment by Bodigrim** [comment]
Closing, the current state of the issue is not actionable.
