### ISSUE TITLE
Add an option to keep symlinks when unpacking

### ISSUE THREAD

**Issue by hasufell** [haskell/tar#63]
Haskell tar currently emulates symlinks by copying:

https://github.com/haskell/tar/blob/a0d722c1f6052bf144017d131a715ea1ae599964/Codec/Archive/Tar/Unpack.hs#L110-L113

This is probably the most cross-platform way, but on platforms where symlinks are known to work, there should be a version of `unpack` that just creates the correct symlinks.

Note that tar currently also cannot extract archives with broken symlinks (because it cannot copy something that doesn't exist). This new version `unpack' :: Exception e => Bool -> FilePath -> Entries e -> IO ()` would not suffer from this problem either.

New windows versions seems to support symlinks: https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#g:6

----

The implementation isn't hard, but this needs to be decided first as part of the public API.

**Comment by Bodigrim** [comment]
I tend to avoid providing an API with both `foo` and `foo'`, which are almost identical, but not quite the same. This will be a constant source of users' confusion. 

Is there a reason to stick to a current behaviour of `unpack` (except for compatibility with ancient `directory`)? Could we create symlinks by default?

**Comment by hasufell** [comment]
> Could we create symlinks by default?

Well, I don't know if all windows versions have this. The directory documentation reads like not all do and that it's filesystem dependent (even worse) and may require administrator privileges. So I don't think this is generally safe.

> I tend to avoid providing an API with both foo and foo', which are almost identical, but not quite the same. This will be a constant source of users' confusion.

I disagree, because I prefer to not break existing API, especially when adding experimental features. The naming can be improved.

**Comment by hasufell** [comment]
The only question mark here is really windows, I see the following solutions:

1. provide a separate `unpack'`: breaks no API, can be marked experimental
2. add a configuration parameter to existing `unpack` to toggle symlink behavior: will break existing API, but avoid a separate function... I'm not a fan
3. make symlink recreation default for unix and for windows:
    - make it default as well and fail hard if the system doesn't support symlinks (pretty rough)
    - make it default, but fall back to file copying (safe, but may be quite surprising)
    - always use file copying on windows (diverging behavior between platforms)

We can maybe have a look how other cross-platform tar implementations handle this?

**Comment by hasufell** [comment]
python seems to go with the fallback option:

https://github.com/python/cpython/blob/9350cc02f862dd93aaaf78feb69fb0a102d3099c/Lib/tarfile.py#L2232-L2256

**Comment by hasufell** [comment]
rust seems to just fail: https://github.com/alexcrichton/tar-rs/blob/f07b3c15e398a76a627e77b49952d44c5d5880d8/src/entry.rs#L495-L528

**Comment by hasufell** [comment]
Implemented in my existing PR:

* https://github.com/haskell/tar/pull/50/commits/4b011961b1799030ee86594ce16d29d485e704a3
* https://github.com/haskell/tar/pull/50/commits/a71015fb335d0798b1dfe759def855891177784c
