### ISSUE TITLE
Make 0.5.x branch the default

### ISSUE THREAD

**Issue by phadej** [haskell/tar#68]
... or release 0.6.

IMO the major release is not worth the change it includes.

**Comment by Bodigrim** [comment]
Unfortunately I don't have any bandwidth to maintain two branches of `tar`, and `master` has accumulated 30 commits atop of `0.5.x`. Asking people to adjust bounds once per 6 years does not strike me as unreasonable, I'm happy to release `tar-0.6` if there is a demand.

**Comment by phadej** [comment]
Probably, it just seems that the only breaking change is

*Add offending path as new field to TarBombError constructor*

```diff
 - data TarBombError TarBombError :: FilePath -> TarBombError
 + data TarBombError TarBombError :: FilePath -> FilePath -> TarBombError
```

But maybe updating bounds is not that bad.
