### ISSUE TITLE
Controlling the initial tar path

### ISSUE THREAD

**Issue by hasufell** [haskell/tar#9]
I have a use case where I want to pack the directory I am currently in _without_ leaving it. I also want to control the topmost directory name inside the tar archive. This is useful for e.g. creating a tar file from a darcs repository and make the topmost tar directory `<reponame>-<version>` or somesuch. The `pack` function didn't really let me do that and I didn't want to reverse-fix the `Entry`s either.

So I came up with something like this:
http://hub.darcs.net/maerwald/darcsden-dist/browse/src/DarcsDen/Handlers/RepoHandlerUtils/Dist.hs#77

``` hs
-- |Packs a directory recursively but let's us specify the initial parent
-- directory inside the tar archive. This just constructs the low-level
-- Entry list though, which can be later used to construct a real tar
-- archive. That can be useful if we want to build our tar archive
-- from multiple independent directories.
--
-- E.g. 'packDirectory "/foo/bar" "baz-1.2"' will pack the directory
-- "/foo/bar" (and all its subdirectories) in the tar archive as
-- "baz-1.2/foo/bar".
packDirectory :: FilePath -- ^ path to pack
              -> String   -- ^ parent directory/path inside the tar archive
              -> [String] -- ^ ignore list
              -> IO [Entry]
packDirectory rootdir tarDir iL = do
  dirc <- getDirectoryContents rootdir
  let dirc' = filter (`notElem` iL') dirc
  entries <- sequence
        [ do
            isDir   <- doesDirectoryExist filePath
            tarPath <- either fail return $ toTarPath isDir relFPath
            if isDir
               then packDirectoryEntry filePath tarPath
               else packFileEntry      filePath tarPath
          | d <- dirc'
          , let filePath = rootdir </> d
                relFPath = tarDir </> d ]
  subDirs       <- filterM (\x -> doesDirectoryExist $ rootdir </> x)
                           dirc'
  subdirEntries <- mapM (\x -> packDirectory (rootdir </> x)
                                 (tarDir </> x) iL)
                               subDirs
  return (entries ++ concat subdirEntries)
    where
      -- we always ignore these directories
      iL' = iL ++ ["..", "."]
```

Is it possible that the idea of controlling the initial tar path can somehow be implemented in the library? Or did I miss something in the API?

**Comment by dcoutts** [comment]
Doesn't the `pack` function do exactly this?

https://hackage.haskell.org/package/tar-0.4.2.2/docs/Codec-Archive-Tar.html#v:pack

You'd specify the base dir as being the parent dir containing the repo, and then one dir to pack which is the repo dir name. For example `pack "/foo/bar" "baz-1.2"`.

Am I missing something?

**Comment by hasufell** [comment]
I don't think so. It requires `/foo/bar` to be present on the filesystem, which is not the case. This is about controlling the basedir _inside_ the tar archive, completely unrelated to the original filesystem.

**Comment by dcoutts** [comment]
Ohh, I see. Then I think you can do it more simply like this:

```
packRepo :: FilePath -> FilePath -> IO [Tar.Entry]
packRepo repoRoot fakeBaseDir = do
    relpaths <- Tar.getDirectoryContentsRecursive repoRoot
    sequence
      [ do tarpath <- either fail return (Tar.toTarPath isDir fakepath)
           if isDir then Tar.packDirectoryEntry realpath tarpath
                    else Tar.packFileEntry      realpath tarpath
      | relpath <- relpaths
      , let isDir    = FilePath.hasTrailingPathSeparator relpath
            realpath = repoRoot </> relpath
            fakepath = fakeBaseDir </> relpath
      ]
```

Given that we do provide `packFileEntry` and `packDirectoryEntry` which do provide full control over the path inside the tar archive, completely independently of the real path outside, then I think that's probably enough. Otherwise I fear we'll end up with a profusion of different special-purpose variants.
