### ISSUE TITLE
[htar] Find an alternative to bzlib

### ISSUE THREAD

**Issue by hasufell** [haskell/tar#92]
* https://github.com/hackage-trustees/bzlib/issues/4
* https://github.com/haskell/security-advisories/issues/155

It is an unmaintained mess.

**Comment by hasufell** [comment]
bz2 is also vulnerable https://github.com/haskell/security-advisories/issues/156

**Comment by hasufell** [comment]
https://github.com/snoyberg/bzlib-conduit/issues/10 too

**Comment by Bodigrim** [comment]
Fixed upstream in https://hackage.haskell.org/package/bzlib-0.5.2.0
