### ISSUE TITLE
Migrating from 0.5.* to 0.6.*

### ISSUE THREAD

**Issue by erikd** [haskell/tar#97]
Due to other dependencies, I am trying to update some code that used to use `0.5.*` of `tar` and now needs to use `0.6.*`.

The code is:
```
    errors <- H.evalIO $ tarErrors . TAR.checkTarbomb topDir . TAR.read . GZ.decompress
                              <$> LBS.readFile tarPath
```
However the return type for `checkTarbomb` has changed from:
```
    Entries (Either e TarBombError)
```
to
```
    GenEntries FilePath FilePath (Either (Either e DecodeLongNamesError) TarBombError)
```
I found the change log which gives 7 "Examples of migrations", but only two of those 7 examples actually use `checkTarbomb` and even for those two (https://github.com/haskell/hackage-server/commit/6b71d1659500aba50b6a1e48aa53039046720af8 and https://github.com/haskell/cabal/commit/51e6483f95ecb4f395dce36e47af296902a75143), are insufficient for me to migrate the above code.

Clues?

**Comment by erikd** [comment]
My local definition of `tarErrors`:
```
tarErrors
    :: TAR.Entries (Either TAR.FormatError TAR.TarBombError) -> [Either TAR.FormatError TAR.TarBombError]
tarErrors entries = TAR.foldEntries (flip const) id (:) entries []
```

**Comment by erikd** [comment]
When I set `tar ^>= 0.6` in the cabal file, I get the following error:
```
src/Hedgehog/Extras/Test/Network.hs:115:40: error: [GHC-83865]
    • Couldn't match type ‘[ghc-prim-0.11.0:GHC.Types.Char]’
                     with ‘tar-0.6.3.0:tar-internal:Codec.Archive.Tar.Types.TarPath’
      Expected: TAR.Entries TAR.FormatError
                -> TAR.Entries (Either TAR.FormatError TAR.TarBombError)
        Actual: TAR.Entries TAR.FormatError
                -> TAR.GenEntries
                     FilePath
                     FilePath
                     (Either
                        (Either TAR.FormatError TAR.DecodeLongNamesError) TAR.TarBombError)
    • In the first argument of ‘(.)’, namely ‘TAR.checkTarbomb topDir’
      In the second argument of ‘(.)’, namely
        ‘TAR.checkTarbomb topDir . TAR.read . GZ.decompress’
      In the first argument of ‘(<$>)’, namely
        ‘tarErrors . TAR.checkTarbomb topDir . TAR.read . GZ.decompress’
    |
115 |       errors <- H.evalIO $ tarErrors . TAR.checkTarbomb topDir . TAR.read . GZ.decompress <$> LBS.readFile tarPath
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by erikd** [comment]
As suggested by @hasufell , changing the type signature of `tarErrors` to:
```
tarErrors :: TAR.GenEntries tarPath linkTarget e -> [e]
tarErrors entries = TAR.foldEntries (flip const) id (:) entries []
```
fixed it.

**Comment by hasufell** [comment]
I think we're not doing a good enough job at explaining the difference between:

* `GenEntries TarPath LinkTarget e` (equals `Entries e`)
* `GenEntries FilePath FilePath e`

The latter is returned by functions like `checkSecurity`, `checkTarbomb` etc. And it's not obvious how to go back to `Entries e` or what else to do.
